import { Scenario } from '@/types';

export const SCENARIOS: Scenario[] = [
  {
    id: 0,
    name: 'Zombie Apocalypse',
    description: 'The dead have risen and society has collapsed. The world belongs to the undead now. How long can you survive among them?',
    bgFrom: '#d4e4cc',
    bgTo: '#dce8d4',
    textColor: '#2a2a2a',
    accentColor: '#5a7a54',
  },
  {
    id: 1,
    name: 'Ice Age',
    description: 'The earth has frozen over and temperatures have dropped to -40°C. This is the world now. How long can you last in the cold?',
    bgFrom: '#b8d4e8',
    bgTo: '#e8f4f8',
    textColor: '#2a2a2a',
    accentColor: '#5b9ec9',
  },
  {
    id: 2,
    name: 'Desert Island',
    description: 'You are stranded on a remote tropical island with no chance of rescue. This is your life now. How long can you survive?',
    bgFrom: '#f5ead4',
    bgTo: '#b8e8ec',
    textColor: '#2a2a2a',
    accentColor: '#4a98a8',
  },
  {
    id: 3,
    name: 'Volcanic Eruption',
    description: 'Your island is consumed by lava and ash. The air is thick and the landscape is unrecognizable. This is your new world. How long can you endure?',
    bgFrom: '#fde8d4',
    bgTo: '#f8d0b0',
    textColor: '#2a2a2a',
    accentColor: '#c87040',
  },
  {
    id: 4,
    name: 'Deep Space',
    description: 'Your shuttle has crashed on an uninhabited planet light years from earth. No rescue is coming. This is where you live now. How long can you survive?',
    bgFrom: '#dcdff0',
    bgTo: '#eceef8',
    textColor: '#2a2a2a',
    accentColor: '#7880c4',
  },
  {
    id: 5,
    name: 'Medieval Plague',
    description: 'A deadly plague has swept through civilization and society has crumbled. There is no medicine and no authority. This is the world you inhabit. How long can you last?',
    bgFrom: '#f0e8d4',
    bgTo: '#e8dce4',
    textColor: '#2a2a2a',
    accentColor: '#8a6a7a',
  },
  {
    id: 6,
    name: 'Nuclear Winter',
    description: 'A nuclear war has blanketed the sky in ash and radiation. Civilization is gone. This is simply the world now. How long can you survive?',
    bgFrom: '#e0e0d8',
    bgTo: '#d4dcc8',
    textColor: '#2a2a2a',
    accentColor: '#7a8a6a',
  },
  {
    id: 7,
    name: 'Deep Sea Research Station',
    description: 'Your research station is stranded at the bottom of the ocean. There is no hope of returning to the surface. This is your world now. How long can you last?',
    bgFrom: '#c8e8e8',
    bgTo: '#dff5f5',
    textColor: '#2a2a2a',
    accentColor: '#4a9898',
  },
  {
    id: 8,
    name: 'Amazon Jungle',
    description: 'You are deep in the rainforest, far from any trace of civilization, sharing the jungle with whatever else calls it home. How long can you survive here?',
    bgFrom: '#d4ecc8',
    bgTo: '#e8f0d4',
    textColor: '#2a2a2a',
    accentColor: '#5a8a48',
  },
  {
    id: 9,
    name: 'Sahara Desert',
    description: 'You are stranded in the middle of the Sahara. Temperatures reach 50°C and the nearest water source is unknown. This is your reality now. How long can you last?',
    bgFrom: '#fce8d0',
    bgTo: '#f8f0d8',
    textColor: '#2a2a2a',
    accentColor: '#c87830',
  },
  {
    id: 10,
    name: 'Arctic Expedition',
    description: 'You are alone on an ice shelf at the top of the world. No team, no base camp, no way home. This is where you live now. How long can you survive?',
    bgFrom: '#c4dcee',
    bgTo: '#e4f4f8',
    textColor: '#2a2a2a',
    accentColor: '#4a7a9a',
  },
  {
    id: 11,
    name: 'Alien Invasion',
    description: 'Extraterrestrial forces have taken over the planet. Human civilization has fallen. You are living in a world that no longer belongs to your species. How long can you last?',
    bgFrom: '#d4f0d4',
    bgTo: '#e8d8f4',
    textColor: '#2a2a2a',
    accentColor: '#5a9854',
  },
  {
    id: 12,
    name: 'Pandemic',
    description: 'A highly contagious virus has swept the globe and society has broken down. You are alone in a world that is no longer safe. How long can you survive?',
    bgFrom: '#f0f0f0',
    bgTo: '#c0d8c0',
    textColor: '#2a2a2a',
    accentColor: '#608060',
  },
  {
    id: 13,
    name: 'Robot Uprising',
    description: 'AI has turned against humanity and machines now control the world. You are one of the last humans navigating a planet that wants you gone. How long can you last?',
    bgFrom: '#d4d8e8',
    bgTo: '#e8d4d8',
    textColor: '#2a2a2a',
    accentColor: '#7070a8',
  },
  {
    id: 14,
    name: 'Medieval Castle Siege',
    description: 'Your castle has fallen and the enemy now controls the land. You are surviving in the ruins of what was once your home. How long can you endure?',
    bgFrom: '#e4e0d8',
    bgTo: '#f0e0d8',
    textColor: '#2a2a2a',
    accentColor: '#8a6a5a',
  },
  {
    id: 15,
    name: 'Tsunami',
    description: 'A series of massive waves has reshaped the coastline and flooded the land. The world is waterlogged and unrecognizable. This is your reality now. How long can you survive?',
    bgFrom: '#b8d4ee',
    bgTo: '#e0f0f8',
    textColor: '#2a2a2a',
    accentColor: '#4a7aa0',
  },
  {
    id: 16,
    name: 'Solar Flare',
    description: 'A massive solar flare has permanently wiped out all electronics across the globe. The modern world is gone and will not return. How long can you last?',
    bgFrom: '#fef8d4',
    bgTo: '#fde8c4',
    textColor: '#2a2a2a',
    accentColor: '#c89020',
  },
  {
    id: 17,
    name: 'Wild West Outlaw',
    description: 'You are a fugitive in the lawless frontier, hunted and alone in the vast desert. There is no civilization to return to. How long can you survive out here?',
    bgFrom: '#f0e4cc',
    bgTo: '#e8d4a8',
    textColor: '#2a2a2a',
    accentColor: '#8a6030',
  },
  {
    id: 18,
    name: 'Prehistoric Earth',
    description: 'You have been transported back 65 million years. This is the world now — raw, ancient, and indifferent to your existence. How long can you last?',
    bgFrom: '#d8ecc8',
    bgTo: '#e8d8b4',
    textColor: '#2a2a2a',
    accentColor: '#5a7840',
  },
];

export function getTodayScenario(): Scenario {
  const today = new Date();
  const utcDay = Math.floor(
    Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()) / 86400000
  );
  return SCENARIOS[(utcDay + 1) % SCENARIOS.length]; // TODO: remove +1 offset after demo
}
